apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-converter-docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: number-converter-docker-app
  template:
    metadata:
      labels:
        app: number-converter-docker-app
    spec:
      containers:
        - name: number-converter-container
          # Place location path of Docker image here. 
          image: <location path of Docker image>
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

